name: Cache cleanup

on:
  pull_request:
    types: [ closed ]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - name: Delete PR caches
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
        REF: refs/pull/${{ github.event.pull_request.number }}/merge
      run: |
        gh cache list --ref "$REF" --limit 100 --json id --jq '.[].id' |
          xargs -r -n1 gh cache delete
